apiVersion: v1
kind: Service
metadata:
  name: preferences
  labels:
    app: preferences
spec:
  type: NodePort
  ports:
    - port: 9009
      name: preferences
      nodePort: 30400
      protocol: TCP
      targetPort: 9009
  selector:
    app: preferences
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preferences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preferences
  template:
    metadata:
      labels:
        app: preferences
    spec:
      imagePullSecrets:
      - name: local-registry
      containers:
      - name: preferences
        image: local-registry:5000/preferences:0.0.1
        ports:
        - containerPort: 9009
          